Refactor to Single Plugin and Add Carpenter Action
arcalot/arcaflow-plugin-fio pull request #1
Opened 2022-09-28 18:50 UTC by mfleader

## Changes introduced with this PR

Refactor to single plugin and add carpenter github action.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-09-29 08:58 UTC, sandrobonazzola approved these changes
LGTM

2022-10-04 15:14 UTC, ghost approved these changes
Looks ok, but I would prefer to move the splitting the repo into at least a separate commit.

2022-10-07 15:25 UTC, dustinblack requested changes

2022-10-07 15:25 UTC, dustinblack commented on python/.gitignore
> -#From https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
Do you want to move the .gitignore to the repo root instead of deleting it?

2022-10-07 16:22 UTC, mfleader commented on python/.gitignore
> -#From https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
i'll copy it over

2022-10-11 15:46 UTC, ghost commented on .github/workflows/carpenter.yaml
> +  QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
I've added this secret.

2022-10-12 09:10 UTC, sandrobonazzola approved these changes

2022-10-12 11:48 UTC, dustinblack approved these changes

2022-10-12 11:49 UTC, merged